Add links to team prod and qa deployments
ucsb-cs156-f23/proj-organic-f23-6pm-1 pull request #30
Opened 2023-11-16 09:21 UTC by Joseph-Foster

Update the README with links to prod and qa deployments
Closes #29

2023-11-16 22:37 UTC, ErwanDev submitted a review, later dismissed
LGTM, deployment links are correct and running.

2023-11-17 17:21 UTC, andrewpengucsb requested changes, later dismissed

2023-11-17 17:21 UTC, andrewpengucsb commented on README.md
While you're at it, you should change the header of the readme as well to match the repo

2023-11-18 21:52 UTC, chauAlex approved these changes
LGTM

2023-11-19 17:32 UTC, pconrad approved these changes
LGTM

2023-11-19 17:32 UTC, merged