Added Create Page for Courses with storybook and tests
ucsb-cs156-f23/proj-organic-f23-6pm-1 pull request #37
Opened 2023-11-17 09:45 UTC by Joseph-Foster

Added Create Page for Courses with storybook and tests

Deployment link: TODO

Screenshot: TODO

Storybook link: TODO

Closes #14

2023-11-18 19:55 UTC, chauAlex approved these changes, later dismissed
Might want to add some validation for the school term - but I guess this varies by school as well, otherwise LGTM!

2023-11-19 19:22 UTC, pconrad commented
> Might want to add some validation for the school term - but I guess this varies by school as well, otherwise LGTM!

I'm not sure we can make any validation other than "required".   But that sparks an idea for a feature to add:
* Admin can do CRUD operations on a table of schools
* Admin can optionally enter:
  * a regular expression for term to be matched against
  * text with explanation/examples of term format
  * text to be used for error message if/when term doesn't match the regular expression

2023-11-19 21:23 UTC, pconrad commented
> > Might want to add some validation for the school term - but I guess this varies by school as well, otherwise LGTM!
> 
> I'm not sure we can make any validation other than "required". But that sparks an idea for a feature to add:
> 
>     * Admin can do CRUD operations on a table of schools
> 
>     * Admin can optionally enter:
>       
>       * a regular expression for term to be matched against
>       * text with explanation/examples of term format
>       * text to be used for error message if/when term doesn't match the regular expression

I added a new Epic for this

2023-11-19 21:24 UTC, pconrad commented on frontend/src/main/components/Courses/CoursesForm.js
> +    const isodate_regex = /(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d\.\d+)|(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d)|(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d)/i;
Might not need this since the UI element already ensures that datetime format is valid; see code review on earlier PR in the flow.

2023-11-19 21:24 UTC, pconrad commented on frontend/src/main/components/Courses/CoursesForm.js
> +                        {...register("start", { required: true, pattern: isodate_regex })}
```suggestion
                        {...register("start", { required: true})}
```

2023-11-19 21:25 UTC, pconrad commented on frontend/src/main/components/Courses/CoursesForm.js
> +                        {...register("end", { required: true, pattern: isodate_regex })}
```suggestion
                        {...register("end", { required: true })}
```

2023-11-19 21:25 UTC, pconrad requested changes
Same suggestions as earlier PR, otherwise LGTM

2023-11-19 22:06 UTC, chauAlex approved these changes
LGTM

2023-11-21 21:32 UTC, pconrad approved these changes
LGTM!

2023-11-21 21:34 UTC, merged