Toggle Buttons for the User Table
ucsb-cs156-f23/proj-organic-f23-6pm-1 pull request #59
Opened 2023-11-28 23:13 UTC by chauAlex

This PR introduces toggle buttons for the User Table when the showToggleButtons property is true, and gives the ability to give and remove instructor and admin privileges. The AdminUsersPage has it set to true and thus shows the buttons, whereas the Profile Page does not provide a value for the showToggleButtons and thus defaults to false.
<img width="1367" alt="Screen Shot 2023-11-28 at 3 11 20 PM" src="https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/assets/91815430/0e1e311e-569e-45c4-b429-8f9b57f63eaa">
<img width="1050" alt="Screen Shot 2023-11-28 at 3 11 36 PM" src="https://github.com/ucsb-cs156-f23/proj-organic-f23-6pm-1/assets/91815430/1d3ae1a5-9276-4526-b42d-96acfdbe4628">

Link to storybook:

2023-11-29 01:10 UTC, Dagin-Gregory submitted a review, later dismissed
Looks good, I did get a 405 when trying to run toggle admin and instructor on the storybook, but I suspect that's due to there being no backend to support the storybook. (Unable to test on a dokku deployment)

2023-11-29 11:33 UTC, Johnsonchan105 submitted a review, later dismissed
LGTM

2023-11-29 18:20 UTC, pconrad requested changes
Code LGTM.  Could you set up a dokku deployment for this branch and link to it in the PR description?

2023-11-29 19:00 UTC, chauAlex commented
Sure thing, dokku deployment is now up

2023-11-30 02:28 UTC, Joseph-Foster submitted a review, later dismissed
LGTM

2023-11-30 02:33 UTC, chauAlex commented
Note: Once Johnson's branch is merged it should also finish #12

2023-12-01 18:11 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
> +    // Stryker enable all
Should be `// Stryker restore all`

That's true throughout the code base.

2023-12-01 18:21 UTC, pconrad requested changes
So, there is one thing that you must fix:
* `// Stryker enable all` is incorrect (notwithstanding the many examples in the code, all of which eventually need to be corrected.  The correct directive is `// Stryker restore all`

Then there is another that will greatly improve the User Experience. Right now, toggling a status causes a full page refresh. But that's unnecessary.   The way to get the page to update without forcing a refresh is this:

Replace this line of code in `AdminUsersPage.js`

```js
const { data: users } = useUsers();
```

With a call to `useBackend`, like this:

```js
 const { data: users, error: _error, status: _status } =
        useBackend(
            // Stryker disable next-line all : don't test internal caching of React Query
            ["/api/admin/users"],
            // Stryker disable next-line StringLiteral,ObjectLiteral : since "GET" is default, "" is an equivalent mutation
            { method: "GET", url: "/api/admin/users" },
            // Stryker disable next-line all
            []
        );
```   


The reason this is important is that `useUsers` (which should not have been written in the first place) doesn't use React Query Library properly; in particular it doesn't set a caching key for retrieving the users.

You are correctly attempting to invalidate the cache key in your POST calls when you toggle the status:
```js
  const toggleAdminMutation = useBackendMutation(
        cellToAxiosParamsToggleAdmin,
        {onSuccess: () => {
            window.location.reload();
        }},
        ["/api/admin/users"]
    );
```

But for that to work, the  cache key you invalidate,  `["/api/admin/users"]` in the POST, has to match the cache key on the GET.   useBackend does this properly.  useUsers doesn't.

If you make this change, then it should work without having to force a page refresh.

And, you'll be able to remove the file where useUsers is defined, and where it is tested.

That part is optional, but the other three organic groups did it, so your app will be stand out (in a bad way) if you don't make this change.  It's not required, but it will make your app look better on demo day, which does impact your grade to an extent.

2023-12-01 21:05 UTC, ErwanDev commented
All instances of // Stryker enable all have been replaced with // Stryker restore all. Made the changes needed to remove the unneeded page refresh and deleted useUsers files.

2023-12-01 22:01 UTC, Joseph-Foster approved these changes
LGTM, doesn't refresh page now

2023-12-04 02:00 UTC, pconrad approved these changes

2023-12-04 02:01 UTC, pconrad approved these changes
LGTM!

2023-12-04 02:01 UTC, merged